Sprint 3
Verisana/middle.messenger.praktikum.yandex pull request #11
Opened 2021-10-11 19:27 UTC by Verisana

2021-10-12 10:19 UTC, nickchamel requested changes
Привет! Я не смог проверить работу
![image](https://user-images.githubusercontent.com/28347933/136938023-b5c927c0-ba2c-4148-8d57-ad65003cb887.png)
Убедись, что на нетлифай верная сборка задеплоена, сейчас там какбуд-то 1 или 2 спринт. По коду оставил тебе рекомендации. Работу пока возвращаю. Как поправишь деплой, отправь на ревью -  я гляну, если по заданиям все ок, то работу приму

2021-10-12 10:19 UTC, nickchamel commented on src/api/auth_api.ts
> +        } as IRequestOptions)
Чтобы везде не дублирвоать `withCredentials`, и вообще дефолтные заголовки - их можно вынести в Http Service (Request class у тебя). Только не нужно мешать их с данными (лучше разные аргументы использовать). И если в каком-то методе будут специфичные заголовки, можно их прокидывать, а в Request мержить их с дефолтными.
Второй момент - у тебя везде дублируется type assertion `as IRequestOptions`. Неплохо бы правильно типизировать методы в Request, чтобы не приходилось этого делать

2021-10-12 10:19 UTC, nickchamel commented on src/api/chats_api.ts
> +export class ChatsAPI extends BaseAPI {
Все апи стоит сразу сделать синглтонами. Нет смысла создавать несколько экземпляров каждого.
`export default new ChatsAPI()`

2021-10-12 10:19 UTC, nickchamel commented on src/components/block/block.ts
> +        ) => string
Из компонентов можно возвращать не темплейт, а функцию компиляции темплейта (`Handlebars.compile(template)`). Сам по себе этот вызов всегда вернет один и тот же результат. Нет смысла при каждом ререндере компонентов делать `Handlebars.compile()`

2021-10-12 10:19 UTC, nickchamel commented on src/components/block/block.ts
> +            } else Block.fillComponentId(components, key, value, context, false)
Условия лучше писать полностью
```
if () {
  ...
} else {
  ...
}
```

2021-10-12 10:19 UTC, nickchamel commented on src/components/block/block.ts
> +            }
Если у тебя в рантайме так может получится, что stub есть, а component.content === null, то нельзя тут так выкидывать ошибку, потому что метод compileToDom прекратит работу и то что его вызывало прекратит работу, короче говоря текущая итерация ивент лупа завершится и у тебя в принципе может половина страницы быть отрендерена и все. Так можно делать в лучше случае если это дев-сборка (заводить env-переменные и чекать если сейчас дев сборка). В продакшене так не стоит делать

2021-10-12 10:19 UTC, nickchamel commented on src/components/submitForm/submitForm.ts
> +            throw new Error("Can not show error, because content is null")
Здесь тоже исключение которое потенциально может заблокировать рендер. Я не знаю по событию будет эта функция вызываться или она вызывается внутри класса.

2021-10-12 10:19 UTC, nickchamel commented on src/consts.ts
> +}
Если константы используются только в определенном модуле, то не стоит их делать глобальными. Можно вынести в папку своего модуля.

2021-10-12 10:19 UTC, nickchamel commented on src/controllers/auth_controller.ts
> +            loginPageProps.LoginSubmitForm.showError()
Правильней будет здесь вернуть ошибки, или прокинуть. А в LoginPage сделать try/catch или .catch и оттуда уже показать ошибку. Контроллер не должен знать о таких вещах как конкретные страницы или компоненты.
Он не должен брать пропсы компонента или вызывать его методы.

2021-10-12 10:19 UTC, nickchamel commented on src/controllers/chats_controller.ts
> +            const { page } = router as any
Если под router.page имеется ввиду текущая страница, то она может быть любая, поэтому any здесь имеет прямой смысл. Но опять же мы в методе `get` контроллера чатов. Откуда мы можем знать что это будет страница чатов. А может мы в профиле будем в будущем подгружать чаты или в виджете каком-то на любой странице. Это не задача контроллера. Задача контроллер - связующая передавать данные, уведомлять об изменениях.

2021-10-12 10:19 UTC, nickchamel commented on src/controllers/chats_controller.ts
> +                }
Это тоже не логика контроллера. Это в компоненте при клике нужно сделать в обработчике событий, и там же можно будет в UI нормально ее показать а не `alert`ом

2021-10-12 10:19 UTC, nickchamel commented on src/controllers/chats_controller.ts
> +                )
Вообщем контроллеры было бы неплохо почистить) много лишней логики в них. Здесь максимум можно сайд-эффекты какие-нибудь сделать по типу Router.navigate или Store.dispatch...

2021-10-12 10:19 UTC, nickchamel commented on src/controllers/chats_controller.ts
> +            ).SideChatBar.props as ISideChatBarProps
Очень сложная для чтения конструкция. Вообще вот пример как можно типизировать пропсы компонентов
![image](https://user-images.githubusercontent.com/28347933/136931143-d8b3a54e-4712-4493-901f-7ab0fffad169.png)

2021-10-12 10:19 UTC, nickchamel commented on src/controllers/chats_controller.ts
> +        return undefined
если функция ничего не возвращает, то она возвращает undefined. Явно это можно не указывать

2021-10-12 10:19 UTC, nickchamel commented on src/controllers/messages_controller.ts
> +        messengerPageProps.Messages = messageComponents
Вот тоже яркий пример, что контроллер не должен ничего знать о странице. Смотри - а что если будет задача такая - необходимо будет сделать, что где бы пользователь не находился (на любой странице) нужно будет слушать сокеты и ловить новые сообщения. Если они будут, то показывать модалку (на любой странице) с переходом в чат по клику например.

2021-10-12 10:19 UTC, nickchamel commented on src/controllers/users_controller.ts
> +            window.location.reload()
`window.location.reload()` это костыль
Если ты здесь сетишь юзера в стор, то тогда компонент профиля должен быть подписан на эти данные и при обновлении профиля он должен сделать вызов `setProps` с новыми данным для того, чтобы перерендерить шаблон

2021-10-12 10:19 UTC, nickchamel commented on src/pages/auth/register/register.ts
> +                            click: [router.go.bind(router, urlSlugs.login)]
А зачем это? может проще `() => { router.go(urlSlugs.login) }`

2021-10-12 10:19 UTC, nickchamel commented on src/store.ts
> +        }
У тебя экспортится уже синглтон, это можно убрать

2021-10-12 10:19 UTC, nickchamel commented on src/store.ts
> +        this.eventBus = () => eventBus
Можно просто `this.eventBus = new EventBus()`

2021-10-12 11:34 UTC, Verisana commented
Никита, привет!

Спасибо за проверку. Я посмотрел. У меня, оказывается, не развернулось, потому что осталась ошибка циклической зависимости от ESlint, поэтому скрипт деплоя упал. Вчера это не заметил. Вместе со всеми правками сегодня это поправлю.

Что касается замечаний, я все прочитал, очень интересные и полезные. Но, кажется, много всего придется переделывать :D

2021-10-12 11:56 UTC, Verisana commented on src/api/auth_api.ts
> +        } as IRequestOptions)
Я думал сделать изначально `withCredential = true`, но потом как-то решил, что это типа неожидаемое поведение. Тогда не знал, что мне для всех запросов понадобится прокидывать куки. В общем, сейчас поставил дефолт и разделил `data` и `options`. Получилось гораздо чище.

2021-10-12 12:01 UTC, Verisana commented on src/api/chats_api.ts
> +export class ChatsAPI extends BaseAPI {
Сделано

2021-10-12 12:50 UTC, Verisana commented on src/components/block/block.ts
> +        ) => string
И правда же. Тогда я его убрал в конструктор. Там как-то органичнее смотрится. Спасибо

2021-10-12 12:52 UTC, Verisana commented on src/components/block/block.ts
> +            } else Block.fillComponentId(components, key, value, context, false)
Исправил. Об этом в Практикуме тоже было сказано, но я правда не понимаю. Разве укороченная версия не читается лучше без этих скобок?

Возможно, я просто скучаю по Питоновскому синтаксису :D

2021-10-12 12:54 UTC, Verisana commented on src/components/block/block.ts
> +            }
Я выкидывал в этих местах ошибки, чтобы можно было словить баг. Такое состояние никогда не должно произойти, что `component.content === null`. И тогда думал, что пусть лучше все упадет в продакшне, чем выискивать баг. Наверное, можно просто в лог писать об этом событии, но не прерывать поток. Исправил.

2021-10-12 12:58 UTC, Verisana commented on src/components/submitForm/submitForm.ts
> +            throw new Error("Can not show error, because content is null")
Тоже поменял

2021-10-12 13:04 UTC, Verisana commented on src/consts.ts
> +}
Вынес неиспользуемые константы поближе к используемым модулям

2021-10-12 13:18 UTC, Verisana commented on src/controllers/auth_controller.ts
> +            loginPageProps.LoginSubmitForm.showError()
Спасибо, очень ценное замечание. Как всегда, начинается за здравие, а под конец уже все уровни абстракции мешаются. Наверное, я еще не до конца понял, где заканчивается граница ответственности контроллера. Думал, что туда вообще все закидывают. Теперь сделал так, что выбрасывается ошибка и дальше страница разруливает ситуацию.

2021-10-12 13:59 UTC, Verisana commented on src/controllers/chats_controller.ts
> +            const { page } = router as any
Понял. Создал новый ивент `sideChatsUpdated` в `sideChatBar` и там уже ставлю обновления. Всю лишнюю логику из контроллера вытащил.

2021-10-12 14:06 UTC, Verisana commented on src/controllers/chats_controller.ts
> +                }
Убрал эту логику в функцию messenger'а `createChatClicked`. Не уверен, что там тоже этому место. В контроллере для функции `create` вообще ничего не осталось.

Что касается нормального UI - это дело во времени. Я не успевал сверстать и решил все сделать самым простым способом :)

Надо будет в 4 спринте еще раз с версткой нормально посидеть, а то получилось все вырвиглазно.

2021-10-12 14:08 UTC, Verisana commented on src/controllers/chats_controller.ts
> +                )
Убрал все эти проверки ввода в messenger

2021-10-12 17:18 UTC, nickchamel commented on src/components/block/block.ts
> +            } else Block.fillComponentId(components, key, value, context, false)
Всегда будут люди который скажут так же как ты) но в основном наоборот. Со скобками глаза лучше "бегают" по коду. Плюс если нужно будет дописать что-то то не нужно будет скобки ставить - уже все будет готово, и диффы потом в гите будут лучше читаться. То же и к объектам относится - я у тебя видел в коде, но не стал писать
```
{
  a: 1,
  b: 2
}
```
```
{
  a: 1,
  b: 2,
}
```
Такое правило даже есть у линтеров. Тоже хорошо так делать, потому что диффы будут удобней

2021-10-12 17:19 UTC, nickchamel commented on src/components/block/block.ts
> +            }
Лучше в лог хотя бы да. Потому что поток прервался и остальной код не выполнился. Может что-то не дорендерится, могут какие-то обработчики не навешатся и тп

2021-10-12 17:25 UTC, nickchamel commented
> Никита, привет!
> 
> Спасибо за проверку. Я посмотрел. У меня, оказывается, не развернулось, потому что осталась ошибка циклической зависимости от ESlint, поэтому скрипт деплоя упал. Вчера это не заметил. Вместе со всеми правками сегодня это поправлю.
> 
> Что касается замечаний, я все прочитал, очень интересные и полезные. Но, кажется, много всего придется переделывать :D

Ну смотри это все рекомендации. Основной критерий принятия работы - что-бы все по заданиям было выполнено, я поэтому и говорю, что как деплой поправишь отправь работу, чтобы я посмотрел. А код можешь потихоньку править!

2021-10-12 18:20 UTC, Verisana commented on src/components/block/block.ts
> +            } else Block.fillComponentId(components, key, value, context, false)
Интересно. С диффами достаточно убедительный аргумент. Там и так сложно читать. Поэтому любая мелочь, которая упрощает восприятие, весьма ценна :)

2021-10-12 18:49 UTC, Verisana commented on src/controllers/chats_controller.ts
> +            ).SideChatBar.props as ISideChatBarProps
Фууух, вот это попотеть пришлось. Я все типы переписал из Блок, как ты показал. Вылезли некоторые ошибки из-за роутера, в которых не могу поставить типы, как следует. Установил затычки, но в остальном "похорошела Москва при Собянине".

2021-10-12 18:50 UTC, Verisana commented on src/controllers/chats_controller.ts
> +        return undefined
Я так и делал, но у меня в `TS` начала вылазить ошибка, что надо вернуть `undefined`, вот и пришлось его поставить в этом и других местах

2021-10-12 19:10 UTC, Verisana commented on src/controllers/messages_controller.ts
> +        messengerPageProps.Messages = messageComponents
Согласен. Интуитивно, кажется, понимал, что что-то не то дергать роутер тут и форсить якобы мы на странице `messenger`, но разнести не додумался. Это тоже исправил

2021-10-12 20:00 UTC, Verisana commented on src/controllers/users_controller.ts
> +            window.location.reload()
У меня, оказывается, баг был с апдейтами. Теперь его поправил и этот костыль не нужен. Убрал его

2021-10-12 20:07 UTC, Verisana commented on src/pages/auth/register/register.ts
> +                            click: [router.go.bind(router, urlSlugs.login)]
Для единообразия. В некоторых местах неизвестны параметры заранее, поэтому все сделал через `bind()`. Но твоя конструкция лучше читается. Исправил в роутерах :)

2021-10-12 20:08 UTC, Verisana commented on src/store.ts
> +        }
Убрал

2021-10-12 20:09 UTC, nickchamel commented on src/controllers/chats_controller.ts
> +        return undefined
А. Обычно пишут `: Promise<void>`, тогда не надо будет явно возвращать

2021-10-12 20:12 UTC, Verisana commented on src/store.ts
> +        this.eventBus = () => eventBus
Это было в практикуме. Мы спрашивали Егора [наставника] типа зачем в функцию прятать это. Он пояснил, что это:

> Это сделано, чтобы обеспечить “приватность” — переменную `eventBus`  нельзя будет переопределить снаружи, только метод `this.evntBus`

Вот и оставил, как там было :)

2021-10-12 20:45 UTC, Verisana commented
Не, не, не. Код ревью - это моя самая любимая часть работы и хрошее место для роста. Не могу проти мимо "рекомендаций". Я все пожелания учел и нетлифай вроде тоже сейчас работает. Самое жесткое было - это все типы проставить. Не ожидал сегодня этим заняться, но теперь все стало намного чище :)

2021-10-13 10:27 UTC, nickchamel requested changes
Привет! Давай поправим немного по заданиям и можно будет двигаться дальше:
1. При обновлении страницы она должна загружаться (это настройки нетлифая, netlify.toml - надо чтобы всегда index.html отдавался)
![image](https://user-images.githubusercontent.com/28347933/137115307-0c0ca12e-0eb1-48b2-9551-b35ef676db59.png)
2. После выделения чата, невозможно выделить другой (ничего не происходит, сообщения из другого чата не появляются)
3. Если выделить другой чат и после этого отправить сообщение - оно не отправляется

2021-10-13 10:27 UTC, nickchamel commented on src/components/block/block.ts
> +        const props = this.render()[1]
Так читаемей будет
`const [, props] = this.render()`

2021-10-13 10:27 UTC, nickchamel commented on src/router/router.ts
> +        // @ts-expect-error
Ну дженерик тип T нельзя присвоить конкретному типу Props, стоит думать таким образом что в use будет приходить любой компонент (any), поэтому в таких моментах нормально использовать тип any

2021-10-13 10:27 UTC, nickchamel commented on src/router/utils.ts
> +        [destination]: layoutFactory<Props>(pages[pageName])
Здесь тоже any пропсы могут быть.
Суть та же - дженерик это неизвестный заранее тип, поэтому нельзя его "присваивать" к определенному

2021-10-13 10:27 UTC, nickchamel commented on src/store.ts
> +        this.eventBus = () => eventBus
Хз чем это помогает, в Block ведь именно этот метод и вызывается для сабмита ивентов, если мы его переопределим, то один фиг все сломается

2021-10-13 11:14 UTC, Verisana commented on src/components/block/block.ts
> +        const props = this.render()[1]
Я сначала так хотел, потом не вспомнил синтаксис и сделал через индекс :D
Исправил

2021-10-13 11:14 UTC, Verisana commented on src/router/router.ts
> +        // @ts-expect-error
Везде проставил тут any. Но я что-то после всех этих предпреждений не очен люблю `any`. Но, видимо, от него никуда не деться

2021-10-13 11:15 UTC, Verisana commented on src/router/utils.ts
> +        [destination]: layoutFactory<Props>(pages[pageName])
Исправил

2021-10-13 11:18 UTC, Verisana commented
Все, работает теперь.

1. Проставил редиректы в нетлифай.
2. Там все сломалось, когда не доглядел и везде синглтон поставил. А у меня `MessagesAPI` новый создается на каждую смену чата, поэтому все сломалось. Теперь вроде ок.
3. Сообщения тоже отправляются теперь

2021-10-13 11:44 UTC, nickchamel approved these changes
Отлично! Работу принял. Успехов в дальнейшем!

2021-10-13 15:31 UTC, merged